// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkudgjfjjbaxxsbzphdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdWRnamZqamJheHhzYnpwaGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDkyMjAsImV4cCI6MjA2NDI4NTIyMH0.J0ISqAE2CC-lWv-YeAHHh50y31IqAvaLYc7NXt2S448";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);